theme: minima
title: Argelio's Blog
author: Argelio Santos
email: Argelio.Santos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Join me in this journey as we learn how to work, code and collaborate using GitHub

# social links
twitter_username: 6elo # DO NOT include the @ character, or else the build will fail!
github_username:  ArgelioSantos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
