theme: minima
title: Professional Development Daily Updates
author: Argelio Santos
email: Argelio.Santos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  See the step by step progress in learning to code and collaborate using GitHub

# social links
twitter_username: 6elo # DO NOT include the @ character, or else the build will fail!
github_username:  ArgelioSantos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
